### PR TITLE
Updates to BAS package

### PR DESCRIPTION
**Pull request by merliseclyde**
Quanli

I have made a number of changes to the package (bug fixes and additional features)  Would you please merge them with the master under our account so that they are synced.

best,
Merlise

### CODE REVIEW

**Comment by QuanliWang** [comment]
Sure. I am at airport and will try it and let you know as soon as I get my hands on it.
Best,
Quanli

**Comment by merliseclyde** [comment]
No rush !  I am  just using git hub more :-)

Cheers,
Merlise

From:  QuanliWang notifications@github.com
Reply-To:  QuanliWang/BAS
<reply+0005de14bcb0158e2d48e4428cf0fb29d79f808a393a806592cf0000000111ef85649
2a169ce061bce79@reply.github.com>
Date:  Friday, August 21, 2015 at 8:33 PM
To:  QuanliWang/BAS BAS@noreply.github.com
Cc:  Merlise  Clyde clyde@stat.duke.edu
Subject:  Re: [BAS] Updates to BAS package (#1)

Sure. I am at airport and will try it and let you know as soon as I get my
hands on it. 
Best, 
Quanli 

> On Aug 21, 2015, at 8:29 PM, Merlise Clyde notifications@github.com wrote:
> 
> Quanli 
> 
> I have made a number of changes to the package (bug fixes and additional
> features) Would you please merge them with the master under our account so that
> they are synced. 
> 
> best, 
> Merlise 
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/QuanliWang/BAS/pull/1
> 
> Commit Summary 
> 
> updated date 
> updated BAS to include logistic models; fixed bugs
> Added Changelog for version 1.04
> added function to create glm structure for imporved readibility
> modified log marginal files to pass in glm family structure
> forgot bayesglm.c
> changed mtherr.c to use warning() rather than Rprintf
> no real change 
> rmoved MCMC iterations
> fixed Burnin.iterations issue as MCMC.iterations was ignored; need to modify
> still 
> provided warning if model is not full rank as dimenion of vector is reduced
> and not equal to p 
> started to work on glm
> changed order 
> changed beta in example
> removed Rprint statements
> removed print 
> cleaned up cod and moved des to .h
> removed print 
> created header file for common calls
> removed print 
> deleted as version no longer compatible with glm_bas; use bayesglm instead
> deleted as version no longer compatible with glm_bas; use bayesglm instead
> allow glmfamily to be passed in from calling function; glm_bas no longer
> callable from R directly
> allow glmfamily to be passed in from calling function
> changed glmfamily from SEXP
> changed glmfamily from SEXP
> cleaned up print 
> added needs compile
> added marg-eplogp option for initprobs for more efficient storage with MCMC
> added marg-eplogp option for initprobs for more efficient storage with MCMC
> begin to add thinning - not implemented yet
> added thinning 
> changed Burnin.iterations to MCMC.iterations as currently no iterations are
> dropped 
> cleaned up formatting
> switched MCMC to MCMC_old and MCMC_new to MCMC
> added shrinkage and posterior mean for the intercept to the output
> added updates for version 1.05
> fixed bug in posterior expectaion of the shrinkage term
> removed unused variables
> modified SetModel1 and SetModel2 for adding shrinkage and intercept
> cleaned format 
> added Laplace Approximation to 1F1
> added Laplace Approximation to 1F1
> added Laplace Approximation to 1F1
> added Laplace Approximation to 1F1
> added Laplace Approximation to 1F1
> added function for pos x
> added function for pos x
> added function for pos x
> R function to call Cephes
> R function to call Cephes
> R function to call Cephes
> R function to call Cephes
> R function to call Cephes
> added option to switch using Cephes or Laplace approx in 1F1 function
> switch for Laplace in 1F1
> File Changes 
> 
> M CHANGELOG (75) 
> M DESCRIPTION (45)
> M NAMESPACE (2) 
> M R/bas.R (207) 
> M R/bas.gglm.R (83)
> M R/eplogprob.R (33)
> D R/gglm.R (58) 
> M R/glm-fit.R (6)
> A R/hypergeometric1F1.R (7)
> M R/predict.bma.R (3)
> D R/zzz.R (3) 
> M inst/CITATION (4)
> M man/BAS-package.Rd (19)
> M man/EB.global.Rd (8)
> M man/bas.Rd (115)
> M man/bas.glm.Rd (62)
> M man/bayesglm.Rd (8)
> M man/coefficients.bma.Rd (8)
> A man/eplogprob-marg.Rd (61)
> D man/gglm.fit.Rd (46)
> M man/update.bma.Rd (37)
> M src/amcmc.c (18)
> A src/bas-glm.h (32)
> M src/bayesglm.c (41)
> M src/deterministic.c (3)
> M src/family.c (174)
> M src/family.h (29)
> D src/glm.c (204)
> M src/glm_deterministic.c (41)
> M src/glm_fit.c (33)
> M src/glm_lpy.c (71)
> M src/glm_mcmc.c (175)
> M src/glm_mcmcbas.c (201)
> D src/glm_posisearch.c (595)
> M src/glm_sampleworep.c (51)
> M src/hyperg.c (2)
> M src/hypergeometric1F1.c (118)
> M src/mcmc.c (15)
> M src/mcmc_new.c (122)
> M src/mcmcbas.c (14)
> M src/mtherr.c (4)
> M src/posisearch.c (6)
> M src/r_multi_norm.c (2)
> M src/tree-structures.c (13)
> Patch Links: 
> 
> https://github.com/QuanliWang/BAS/pull/1.patch
> https://github.com/QuanliWang/BAS/pull/1.diff
>  
> Reply to this email directly or view it on GitHub.


Reply to this email directly or view it on GitHub
https://github.com/QuanliWang/BAS/pull/1#issuecomment-133601995 .

**Comment by QuanliWang** [comment]
Hi Merlise,
I could not find the changed branch from git hub.  I am just wondering if you keep that local now. You can either send me the update or create a branch and sync and then create a pull request.
Best,
Quanli

**Comment by QuanliWang** [comment]
Sorry. Found it from the link. It is merged now.
Best,
Quanli

**Pull request merged**
